name: Duels
version: '1.0'
main: hu.jgj52.duels.Duels
api-version: '1.21'
authors: [ JGJ52 ]
depend:
  - WorldEdit
  - WorldGuard
commands:
  duel:
    permission: duels.command.duel
  acceptduel:
    permission: duels.command.acceptduel
  kit:
    permission: duels.command.kit
  arena:
    permission: duels.command.arena
  editkit:
    permission: duels.command.editkit
  forfeit:
    permission: duels.command.forfeit
  leave:
    permission: duels.command.leave
  queue:
    permission: duels.command.queue