name: Duels
version: '1.0'
main: hu.jgj52.duels.Duels
api-version: '1.21'
authors: [ JGJ52 ]
commands:
  duel:
    permission: duels.command.duel
  acceptduel:
    permission: duels.command.acceptduel
  kit:
    permission: duels.command.kit